/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuemQueroMeTornarRouteImport } from './routes/_authenticated/quem-quero-me-tornar'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedMomentosRouteImport } from './routes/_authenticated/momentos'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedLinhaDoTempoRouteImport } from './routes/_authenticated/linha-do-tempo'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedEvolucaoRouteImport } from './routes/_authenticated/evolucao'
import { Route as AuthenticatedDesafioFinanceiroRouteImport } from './routes/_authenticated/desafio-financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCartaRouteImport } from './routes/_authenticated/carta'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuemQueroMeTornarRoute =
  AuthenticatedQuemQueroMeTornarRouteImport.update({
    id: '/quem-quero-me-tornar',
    path: '/quem-quero-me-tornar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMomentosRoute = AuthenticatedMomentosRouteImport.update({
  id: '/momentos',
  path: '/momentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinhaDoTempoRoute =
  AuthenticatedLinhaDoTempoRouteImport.update({
    id: '/linha-do-tempo',
    path: '/linha-do-tempo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvolucaoRoute = AuthenticatedEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafioFinanceiroRoute =
  AuthenticatedDesafioFinanceiroRouteImport.update({
    id: '/desafio-financeiro',
    path: '/desafio-financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartaRoute = AuthenticatedCartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carta': typeof AuthenticatedCartaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desafio-financeiro': typeof AuthenticatedDesafioFinanceiroRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/linha-do-tempo': typeof AuthenticatedLinhaDoTempoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/momentos': typeof AuthenticatedMomentosRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/quem-quero-me-tornar': typeof AuthenticatedQuemQueroMeTornarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carta': typeof AuthenticatedCartaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desafio-financeiro': typeof AuthenticatedDesafioFinanceiroRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/linha-do-tempo': typeof AuthenticatedLinhaDoTempoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/momentos': typeof AuthenticatedMomentosRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/quem-quero-me-tornar': typeof AuthenticatedQuemQueroMeTornarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/carta': typeof AuthenticatedCartaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desafio-financeiro': typeof AuthenticatedDesafioFinanceiroRoute
  '/_authenticated/evolucao': typeof AuthenticatedEvolucaoRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/linha-do-tempo': typeof AuthenticatedLinhaDoTempoRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/momentos': typeof AuthenticatedMomentosRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/quem-quero-me-tornar': typeof AuthenticatedQuemQueroMeTornarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carta'
    | '/configuracoes'
    | '/dashboard'
    | '/desafio-financeiro'
    | '/evolucao'
    | '/habitos'
    | '/linha-do-tempo'
    | '/metas'
    | '/momentos'
    | '/planejamento'
    | '/quem-quero-me-tornar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carta'
    | '/configuracoes'
    | '/dashboard'
    | '/desafio-financeiro'
    | '/evolucao'
    | '/habitos'
    | '/linha-do-tempo'
    | '/metas'
    | '/momentos'
    | '/planejamento'
    | '/quem-quero-me-tornar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/carta'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/desafio-financeiro'
    | '/_authenticated/evolucao'
    | '/_authenticated/habitos'
    | '/_authenticated/linha-do-tempo'
    | '/_authenticated/metas'
    | '/_authenticated/momentos'
    | '/_authenticated/planejamento'
    | '/_authenticated/quem-quero-me-tornar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quem-quero-me-tornar': {
      id: '/_authenticated/quem-quero-me-tornar'
      path: '/quem-quero-me-tornar'
      fullPath: '/quem-quero-me-tornar'
      preLoaderRoute: typeof AuthenticatedQuemQueroMeTornarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/momentos': {
      id: '/_authenticated/momentos'
      path: '/momentos'
      fullPath: '/momentos'
      preLoaderRoute: typeof AuthenticatedMomentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/linha-do-tempo': {
      id: '/_authenticated/linha-do-tempo'
      path: '/linha-do-tempo'
      fullPath: '/linha-do-tempo'
      preLoaderRoute: typeof AuthenticatedLinhaDoTempoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evolucao': {
      id: '/_authenticated/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof AuthenticatedEvolucaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafio-financeiro': {
      id: '/_authenticated/desafio-financeiro'
      path: '/desafio-financeiro'
      fullPath: '/desafio-financeiro'
      preLoaderRoute: typeof AuthenticatedDesafioFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta': {
      id: '/_authenticated/carta'
      path: '/carta'
      fullPath: '/carta'
      preLoaderRoute: typeof AuthenticatedCartaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartaRoute: typeof AuthenticatedCartaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesafioFinanceiroRoute: typeof AuthenticatedDesafioFinanceiroRoute
  AuthenticatedEvolucaoRoute: typeof AuthenticatedEvolucaoRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedLinhaDoTempoRoute: typeof AuthenticatedLinhaDoTempoRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMomentosRoute: typeof AuthenticatedMomentosRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedQuemQueroMeTornarRoute: typeof AuthenticatedQuemQueroMeTornarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartaRoute: AuthenticatedCartaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesafioFinanceiroRoute: AuthenticatedDesafioFinanceiroRoute,
  AuthenticatedEvolucaoRoute: AuthenticatedEvolucaoRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedLinhaDoTempoRoute: AuthenticatedLinhaDoTempoRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMomentosRoute: AuthenticatedMomentosRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedQuemQueroMeTornarRoute: AuthenticatedQuemQueroMeTornarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
